# Generated by Django 3.0.7 on 2020-07-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('adjunto', models.CharField(blank=True, max_length=20, null=True)),
                ('task', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True)),
                ('tag', models.CharField(blank=True, max_length=15, null=True)),
                ('type', models.CharField(choices=[('Primero', 'Tipo1'), ('Segundo', 'Tipo2'), ('Tercero', 'Tipo3')], default='Primero', max_length=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
